/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    Content: typeof import('./src/components/Content.vue')['default']
    FileItem: typeof import('./src/components/FileItem.vue')['default']
    FolderItem: typeof import('./src/components/FolderItem.vue')['default']
    RootFolderItem: typeof import('./src/components/RootFolderItem.vue')['default']
    RootFolderList: typeof import('./src/components/RootFolderList.vue')['default']
  }
}
