/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardGroup: typeof import('bootstrap-vue-next/components/BCard')['BCardGroup']
    BCardImg: typeof import('bootstrap-vue-next/components/BCard')['BCardImg']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    Content: typeof import('./src/components/Content.vue')['default']
    ContentList: typeof import('./src/components/ContentList.vue')['default']
    FileItem: typeof import('./src/components/FileItem.vue')['default']
    FileList: typeof import('./src/components/FileList.vue')['default']
    FolderItem: typeof import('./src/components/FolderItem.vue')['default']
    FolderTree: typeof import('./src/components/FolderTree.vue')['default']
    RecursiveFolderItem: typeof import('./src/components/RecursiveFolderItem.vue')['default']
    RootFolderItem: typeof import('./src/components/RootFolderItem.vue')['default']
    RootFolderList: typeof import('./src/components/RootFolderList.vue')['default']
    SubfolderList: typeof import('./src/components/SubfolderList.vue')['default']
  }
}
