services:
  mysql:
    image: mysql:8.0
    container_name: windows-explorer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: windows-explorer
      MYSQL_USER: user
      MYSQL_PASSWORD: xxxxxxxxxxxxxxxxx
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - explorer-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: windows-explorer-backend
    environment:
      - DB_HOST=mysql
      - DB_PORT=33060
      - DB_USERNAME=user
      - DB_PASSWORD=xxxxxxxxxxxxxxxxx
      - DB_NAME=windows-explorer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - explorer-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: windows-explorer-frontend
    ports:
      - "8088:80"
    depends_on:
      - backend
    networks:
      - explorer-network
    restart: always

volumes:
  mysql-data:
    name: mysql-volume

networks:
  explorer-network:
    name: explorer-network
